openapi: 3.1.0
info:
  version: '1.0'
  title: sleep
  summary: hi
  description: hello
servers:
  - url: 'http://localhost:3000'
    description: ''
paths:
  '/users/{userId}':
    get:
      summary: Get User Info by User ID
      description: Retrieve the information of the user with the matching user ID.
      operationId: get-users-userId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '100':
          description: Continue
          content:
            application/json:
              schema:
                type: object
                properties:
                  nhuigi:
                    type: object
                    properties:
                      mhbjih:
                        x-sl-error-message: Unable to find resolutions file
                      yjguih:
                        type: string
                  gugj:
                    type: string
                required:
                  - nhuigi
                  - gugj
          headers:
            header-0:
              schema:
                type: string
              description: m nbvhgcghj
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
          headers:
            header-0:
              schema:
                type: string
        '404':
          description: User Not Found
      servers:
        - url: 'http://localhost:3000'
          description: ''
    patch:
      summary: Update User Information
      description: Update the information of an existing user.
      operationId: patch-users-userId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Patch user properties to update.
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      servers:
        - url: 'http://localhost:3000'
          description: ''
    delete:
      summary: Your DELETE endpoint
      operationId: delete-users-userId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses: {}
      servers:
        - url: 'http://localhost:3000'
          description: ''
    trace:
      summary: Your TRACE endpoint
      operationId: trace-users-userId
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses: {}
      servers:
        - url: 'http://localhost:3000'
          description: ''
  /user:
    post:
      summary: Create New User
      description: Create a new user.
      operationId: post-user
      requestBody:
        description: Post the necessary fields for the API to create a new user.
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      servers:
        - url: 'http://localhost:3000'
          description: ''
    patch:
      summary: Your PATCH endpoint
      operationId: patch-user
      responses: {}
      servers:
        - url: 'http://localhost:3000'
          description: ''
components:
  schemas:
    User:
      type: object
      title: User
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          examples:
            - '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          description: The date that the user was created.
          format: date
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
